(function(){
function boot(){
 const trigger=document.getElementById('avatarTriggerBtn'); if(!trigger||document.getElementById('claimoMayaDrawer'))return;
 const css=`.claimo-maya-drawer{position:fixed;left:24px;bottom:92px;z-index:95;width:min(390px,calc(100vw - 32px));height:min(560px,calc(100vh - 140px));display:none;flex-direction:column;overflow:hidden;background:rgba(10,13,17,.98);border:1px solid rgba(0,255,135,.35);border-radius:24px;box-shadow:0 25px 80px rgba(0,0,0,.65);backdrop-filter:blur(18px)}.claimo-maya-drawer.active{display:flex}.claimo-maya-head{display:flex;align-items:center;justify-content:space-between;padding:14px 16px;border-bottom:1px solid rgba(255,255,255,.1)}.claimo-maya-profile{display:flex;align-items:center;gap:10px}.claimo-maya-avatar{width:42px;height:42px;border-radius:50%;object-fit:cover;border:2px solid #00ff87}.claimo-maya-title{font-size:13px;font-weight:900;color:#fff}.claimo-maya-status{font-size:10px;color:#00ff87;font-weight:800;margin-top:2px}.claimo-maya-close{background:none;border:0;color:#aaa;font-size:22px;cursor:pointer}.claimo-maya-messages{flex:1;overflow-y:auto;padding:16px;display:flex;flex-direction:column;gap:10px}.claimo-maya-msg{max-width:90%;padding:11px 13px;border-radius:15px;font-size:12px;line-height:1.55}.claimo-maya-msg.bot{align-self:flex-start;background:rgba(255,255,255,.07);border:1px solid rgba(0,255,135,.22);color:#eee}.claimo-maya-msg.user{align-self:flex-end;background:#00ff87;color:#050706;font-weight:700}.claimo-maya-quick{display:flex;flex-wrap:wrap;gap:7px;padding:0 16px 10px}.claimo-maya-quick button{padding:7px 9px;border-radius:999px;border:1px solid rgba(0,255,135,.3);background:rgba(0,255,135,.07);color:#00ff87;font-size:10px;font-weight:800;cursor:pointer}.claimo-maya-input{display:flex;gap:7px;padding:12px;border-top:1px solid rgba(255,255,255,.1)}.claimo-maya-input input{flex:1;min-width:0;padding:10px 11px;border-radius:12px;border:1px solid rgba(255,255,255,.13);background:#07090b;color:#fff;outline:none;font-size:12px}.claimo-maya-input button{width:42px;border:0;border-radius:12px;background:#00ff87;color:#000;font-weight:900;cursor:pointer}@media(max-width:640px){.claimo-maya-drawer{left:16px;bottom:88px;width:calc(100vw - 32px)}}`;
 const s=document.createElement('style');s.textContent=css;document.head.appendChild(s);
 const d=document.createElement('aside');d.id='claimoMayaDrawer';d.className='claimo-maya-drawer';d.innerHTML=`<div class="claimo-maya-head"><div class="claimo-maya-profile"><img class="claimo-maya-avatar" src="avatar-guide.jpg" alt="Maya"><div><div class="claimo-maya-title">Maya <span style="color:#00ff87">• AI Guide</span></div><div class="claimo-maya-status">Online · Claimo Resolution Guide</div></div></div><button class="claimo-maya-close" type="button">×</button></div><div class="claimo-maya-messages" id="claimoMayaMessages"><div class="claimo-maya-msg bot">Hi, I'm Maya. Tell me what went wrong with your order, refund, return, delivery or seller response. I'll help you figure out the next step.</div></div><div class="claimo-maya-quick"><button data-maya="My refund hasn't arrived">Refund not received</button><button data-maya="My return was rejected">Return rejected</button><button data-maya="My item arrived damaged">Damaged item</button><button data-maya="My order never arrived">Order not delivered</button></div><form class="claimo-maya-input" id="claimoMayaForm"><input id="claimoMayaInput" placeholder="Tell Maya what happened…" autocomplete="off"><button type="submit">→</button></form>`;
 document.body.appendChild(d);
 const box=document.getElementById('claimoMayaMessages'),input=document.getElementById('claimoMayaInput');
 function add(t,c){const x=document.createElement('div');x.className='claimo-maya-msg '+c;x.textContent=t;box.appendChild(x);box.scrollTop=box.scrollHeight}
 function reply(q){const t=q.toLowerCase();if(t.includes('refund')||t.includes('money'))return 'For a delayed or rejected refund, keep your order ID, payment proof, refund promise and the complete support conversation. Those details help structure the grievance.';if(t.includes('return'))return 'For a rejected return, keep the rejection message, return-request date, product photos and order details.';if(t.includes('damage')||t.includes('defect')||t.includes('broken'))return 'For a damaged or defective item, keep photos of the product and packaging, delivery date, invoice and your complaint to the seller.';if(t.includes('deliver')||t.includes('arriv')||t.includes('missing'))return 'For an order that never arrived, keep the order confirmation, promised delivery date, tracking history and delivery-status messages.';if(t.includes('seller')||t.includes('support')||t.includes('customer care'))return 'Keep the complete chat or email trail, especially any refusal, closure or ticket number. Claimo can use those facts to structure the grievance.';return 'Tell me what you ordered, what went wrong, and what the seller or platform told you. I can help identify the grievance category and evidence to keep.'}
 function send(q){q=(q||'').trim();if(!q)return;add(q,'user');input.value='';setTimeout(()=>add(reply(q),'bot'),300)}
 trigger.addEventListener('click',()=>{d.classList.toggle('active');if(d.classList.contains('active'))setTimeout(()=>input.focus(),100)});d.querySelector('.claimo-maya-close').onclick=()=>d.classList.remove('active');d.querySelectorAll('[data-maya]').forEach(b=>b.onclick=()=>send(b.dataset.maya));document.getElementById('claimoMayaForm').onsubmit=e=>{e.preventDefault();send(input.value)};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();